# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1f35227e654064a01cfd6791c741c4209b51fa14eaaf160a982e20d78117973c214f2e7e2361ca85124f34970685ceef755ae002f7c4d5b8d06ee5cc9113e3f

test:
  secret_key_base: 38112dff3e618a4fff2861b7c37389fcd848b3cd30bcc98a4fe80d9e6b03b266f696529d164d74fff3002c78051194d393dfa8772509541c30209ad8eab5e275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
