# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bb1682ce3a29047a84eefe313ab6e60b09c5bcbed231ba5851deb89d11b9f686e622092b34994b1d16f43af7d6dfd145e73fb42a053178a0bbadb76e78c8474

test:
  secret_key_base: 484e1de85bd98217a3e0680df35437067995525484cbbcccf9d512788d203fab93f81df7af6f5939f95bc05b3b17a2668335ebfba2f6bb3fa47f39c1aae6bf2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
