# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5899acd72e0081e8bd253af9a15b42c63bdb0179da6e0767f2dd8e301b7bfa21e65b69691453be8d71be1150f1c09dff3380b6e39c72cf0efbe6130d2bd9ce65

test:
  secret_key_base: c78cbe02fd423f3d19631496fc1d89500c8a1a36f645c105d8e1e93f642e3734b87effbd9f6b5d922f69b0f36cfe0eb240bb71a91dd5ec473a3ab78485cee013

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
